// <auto-generated />
using System;
using GP.Focusi.Repository.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GP.Focusi.Repository.Data.Migrations
{
    [DbContext(typeof(FocusiAppDbContext))]
    [Migration("20250516034140_EditChildClassTable")]
    partial class EditChildClassTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GP.Focusi.Core.Entites.Advice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ChildClassID")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildClassID");

                    b.ToTable("Advices");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.ChildClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChildEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassScore")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.FeedBack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChildEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateOfCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Q1ProgramHelpParent")
                        .HasColumnType("int");

                    b.Property<int>("Q2SuitableActivity")
                        .HasColumnType("int");

                    b.Property<int>("Q3ContentUnderstand")
                        .HasColumnType("int");

                    b.Property<string>("Q4behaviurImprovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q5ContinueInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q6RecomendProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q7MostHelpfulPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggestions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.Identity.AppUserChild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ChildScore")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUserChild");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.ParentTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChildEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateOfSubmited")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DistractionRatio")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ParentTests");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.Story", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ChildClassID")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ChildClassID");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManager", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChildMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("int");

                    b.Property<int>("TaskManagerScore")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TaskManagers");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManagerItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChildEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDateAndTimeEnded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("TaskManagerId");

                    b.ToTable("TaskManagerItems");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.Advice", b =>
                {
                    b.HasOne("GP.Focusi.Core.Entites.ChildClass", null)
                        .WithMany("Advice")
                        .HasForeignKey("ChildClassID");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.ChildClass", b =>
                {
                    b.OwnsOne("GP.Focusi.Core.Entites.Games", "Game", b1 =>
                        {
                            b1.Property<int>("ChildClassID")
                                .HasColumnType("int");

                            b1.Property<double>("Duration")
                                .HasColumnType("float");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.HasKey("ChildClassID");

                            b1.ToTable("Classes");

                            b1.WithOwner()
                                .HasForeignKey("ChildClassID");
                        });

                    b.OwnsOne("GP.Focusi.Core.Entites.Videos", "Video", b1 =>
                        {
                            b1.Property<int>("ChildClassID")
                                .HasColumnType("int");

                            b1.Property<int>("CorrectAnswers")
                                .HasColumnType("int");

                            b1.Property<int>("Questions")
                                .HasColumnType("int");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.HasKey("ChildClassID");

                            b1.ToTable("Classes");

                            b1.WithOwner()
                                .HasForeignKey("ChildClassID");
                        });

                    b.Navigation("Game")
                        .IsRequired();

                    b.Navigation("Video")
                        .IsRequired();
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.Story", b =>
                {
                    b.HasOne("GP.Focusi.Core.Entites.ChildClass", null)
                        .WithMany("Story")
                        .HasForeignKey("ChildClassID");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManagerItems", b =>
                {
                    b.HasOne("GP.Focusi.Core.Entites.TaskManager", "TaskManager")
                        .WithMany("Items")
                        .HasForeignKey("TaskManagerId");

                    b.Navigation("TaskManager");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.ChildClass", b =>
                {
                    b.Navigation("Advice");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManager", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
