// <auto-generated />
using System;
using GP.Focusi.Repository.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GP.Focusi.Repository.Data.Migrations
{
    [DbContext(typeof(FocusiAppDbContext))]
    [Migration("20250422221741_addItemsToTaskManager")]
    partial class addItemsToTaskManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManager", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChildMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.Property<int>("TaskManagerScore")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TaskManagers");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManagerItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChildEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDateAndTimeEnded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("TaskManagerId");

                    b.ToTable("TaskManagerItems");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManagerItems", b =>
                {
                    b.HasOne("GP.Focusi.Core.Entites.TaskManager", "TaskManager")
                        .WithMany("Items")
                        .HasForeignKey("TaskManagerId");

                    b.Navigation("TaskManager");
                });

            modelBuilder.Entity("GP.Focusi.Core.Entites.TaskManager", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
